on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
permissions:
  contents: read


name: Release Drafter
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true



permissions:
  contents: write
  pull-requests: read

jobs:
  update_release_draft:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: release-drafter/release-drafter@693d20e7c1ce1a81d3a41962f85914253b518449
        env:
          GITHUB_TOKEN: ${{ github.token }}
