name: Trufflehog Secrets Scan
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
permissions:
  contents: read

  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  trufflehog:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v4
        with:
          fetch-depth: 0
      - uses: trufflesecurity/trufflehog@82df476e759c1448517fac6bfb3677685cdcd78a # v-latest
      - run: trufflehog github --only-verified --no-update
        env:
          GH_TOKEN: \${{ github.token }}
